GET http://localhost:8888/grades/  HTTP/1.1

###

GET http://localhost:8888/grades/8/  HTTP/1.1
###

POST http://localhost:8888/grades/
Content-Type: application/json

{ "id": "8", "name": "Battuguldur", "course": "f", "grade": "100" }

####

DELETE http://localhost:8888/grades/1  HTTP/1.1
###


PUT http://localhost:8888/grades/1
Content-Type: application/json

{ "id": "1", "name": "Battuguldur", "course": "s", "grade": "100" }
